"""initial tables

Revision ID: 61c79ecc3ebb
Revises: 
Create Date: 2026-04-19 03:13:16.764842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c79ecc3ebb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprints',
    sa.Column('fingerprint', sa.String(length=66), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('fingerprint')
    )
    op.create_index(op.f('ix_fingerprints_operator_id'), 'fingerprints', ['operator_id'], unique=False)
    op.create_table('operator_pools',
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('balance_usdc', sa.Float(), nullable=False),
    sa.Column('total_evaluations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('operator_id')
    )
    op.create_table('operators',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_api_key'), 'operators', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operators_api_key'), table_name='operators')
    op.drop_table('operators')
    op.drop_table('operator_pools')
    op.drop_index(op.f('ix_fingerprints_operator_id'), table_name='fingerprints')
    op.drop_table('fingerprints')
    # ### end Alembic commands ###
